update solidity version
sbip-sg/discover pull request #113
Opened 2022-03-07 08:00 UTC by cassc

Update solidity contract version, for details see `benchmarks/verismart/README.md`

2022-03-07 08:05 UTC, taquangtrung commented
@cassc: can you add some description of the PR? 

like update Verismart benchmarks to Solidity 0.8.12

2022-03-07 08:21 UTC, taquangtrung requested changes

2022-03-07 08:21 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/016.sol
> +  function approve(address _spender, uint256 _value)public override returns (bool success){
Do we need to use `override`?

2022-03-07 08:21 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/016.sol
> +  function transferFrom(address _from, address _to, uint256 _value)public override virtual returns(bool success){
Why is this `constant` updated to `public override virtual` while some others are updated to only `public virtual`?

2022-03-09 03:28 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/016.sol
> +  function transferFrom(address _from, address _to, uint256 _value)public override virtual returns(bool success){
Old solidty version does not differentiate interface/abstract contract. 
These updates are checked with `solc` compiler.

2022-03-09 03:43 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/016.sol
> +  function approve(address _spender, uint256 _value)public override returns (bool success){
yes, it's overriding approve method in `Token` contract

2022-03-11 07:31 UTC, taquangtrung requested changes

2022-03-11 07:31 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/cve/2018-12079.sol
> +pragma solidity >=0.7.0;contract owned {
@cassc: can you restore the newline here?
And in many other files

2022-03-11 07:31 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/cve/2018-13169.sol
> +pragma solidity >=0.7.0;contract tokenRecipient { function receiveApproval(address from, uint256 value, address token, bytes extraData) public; }
Need to restore the newline here

2022-03-11 07:31 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/cve/2018-13169.sol
> +pragma solidity >=0.7.0;contract tokenRecipient { function receiveApproval(address from, uint256 value, address token, bytes extraData) public; }
Need to restore the newline here

2022-03-11 07:31 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/cve/2018-13175.sol
> +pragma solidity >=0.7.0;/* 创建一个父类， 账户管理员 */
Restore the newline

2022-03-11 07:31 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/cve/2018-13175.sol
> +pragma solidity >=0.7.0;/* 创建一个父类， 账户管理员 */
Restore the newline

2022-03-11 08:15 UTC, taquangtrung requested changes

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/009.sol
> +        require(!( !safeToAdd(_balances[to], value) ));
remove double !!

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/009.sol
> +        require(!( !safeToAdd(_balances[to], value) ));
double !!

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/010.sol
> -  function assert(bool assertion) internal {
function assert is removed?

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/012.sol
> -    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
Why is this function removed?

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/012.sol
> +        require(! (msg.sender == owner));
This condition is incorrect! Should remove !

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/013.sol
> -    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
Is the name 'allowance' changed to 'transferFrom'?

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/014.sol
> -    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
Why is 'allowance' removed?

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/014.sol
> +        require(! (!super.transfer(owner, amount)));
remove double !!

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/015.sol
> -    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
why is 'allowance' removed?

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/015.sol
> +        require(! (msg.sender != owner));
require (msg.sender == owner)

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/016.sol
> +        require(!(msg.sender!=founder));
change to use ==

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/021.sol
> +        require(! (msg.sender != owner));
use ==

2022-03-11 08:15 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/022.sol
> +        require (a + b >= a) ;
should be > ?

2022-03-11 08:46 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/010.sol
> -  function assert(bool assertion) internal {
new version of solidity already provides assert function

2022-03-11 08:47 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/012.sol
> -    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
ERC20Interface is copied from a standard template, now it's moved to line 25.

2022-03-11 08:48 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/012.sol
> +        require(! (msg.sender == owner));
updated to `require(msg.sender == owner);`

2022-03-11 08:50 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/014.sol
> -    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
no, it's moved to line 25

2022-03-11 08:51 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/015.sol
> -    function allowance(address _owner, address _spender) constant returns (uint256 remaining);
no, it's moved to line 25

2022-03-11 09:46 UTC, taquangtrung requested changes

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/003.sol
> +        require(! (balanceOf[msg.sender] < _value));           // Check if the sender has enough
Should it be more natural like `require(balanceOf[msg.sender] >= _value);` ?

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/003.sol
> +        require(! (balanceOf[_to] + _value < balanceOf[_to])); // Check for overflows
Same for `require(balanceOf[_to] + _value >= balanceOf[_to]);` ?

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/002.sol
> +        require(! (msg.value <= 0 || (block.timestamp + timeLimit) <= block.timestamp) );
Change to `require(msg.value > 0 && (block.timestamp + timeLimit) > block.timestamp);` ?

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/002.sol
> +        require (! (address(this).balance > 0 && !owner.send(address(this).balance)));
```
if (this.balance > 0) {
  require (owner.send(this.blance));
}
```

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/003.sol
> +        require(! (_value > allowance[_from][msg.sender]));   // Check allowance
We also need to replace  `! ... <` by `>=`

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/004.sol
> +        require(! (balanceOf[_to] + _value < balanceOf[_to])); // Check for overflows
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/004.sol
> +        require(! (_value > allowance[_from][msg.sender]));   // Check allowance
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/005.sol
> +        require(!( !safeToAdd(_balances[to], value) ));
remove double !!

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/005.sol
> +        require(!( _balances[msg.sender] < value ));
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/005.sol
> +        require(!( _balances[from] < value ));
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/005.sol
> +        require(!( !safeToAdd(_balances[to], value) ));
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/007.sol
> +        require(!( _balances[msg.sender] < value ));
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/007.sol
> +        require(!( _approvals[from][msg.sender] < value ));
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/009.sol
> +        require(!( _balances[msg.sender] < value ));
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/009.sol
> +        require(!( _balances[from] < value ));
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/009.sol
> +        require(!( _approvals[from][msg.sender] < value ));
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +      require(!(
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +      require(!(
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +      require(!(
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +      require(!(
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +    require(!(balanceMap[address(this)] < amount));
Replace the use of `!` by the suitable operations

2022-03-11 09:46 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +      require(!(balanceMap[msg.sender] < amount));
Replace the use of `!` by the suitable operations

2022-03-14 18:33 UTC, taquangtrung requested changes

2022-03-14 18:33 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/008.sol
> +      require(msg.sender == owner);
delete extra 2 white spaces

2022-03-14 18:33 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/008.sol
> +        spender.receiveApproval(msg.sender, _value, address(this), _extraData);
delete extra 2 white spaces

2022-03-14 18:33 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +      require(msg.sender == owner);
delete 2 extra white spaces

2022-03-14 18:33 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +        spender.receiveApproval(msg.sender, _value, address(this), _stuff);
delete 2 extra whitespaces

2022-03-14 18:33 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +      require(balanceMap[msg.sender] >= amount);
delete 2 extra white spaces

2022-03-14 18:33 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/018.sol
> +        assert (transfer(owner, amount)) ;
why use `assert`? why not use `require` like other migration?

2022-03-14 18:33 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/019.sol
> +        require(!disabled);
eh, should write `require(msg.sender != owner || block.timestamp >= startTime + 365 days || safeSub(balanceOf[msg.sender],_value) > 50000000)`;

2022-03-14 18:33 UTC, taquangtrung commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/019.sol
> +        require(!disabled);
should write the specific condition here

2022-03-15 01:14 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/008.sol
> +        spender.receiveApproval(msg.sender, _value, address(this), _extraData);
deleted

2022-03-15 01:14 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +      require(msg.sender == owner);
deleted

2022-03-15 01:15 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +        spender.receiveApproval(msg.sender, _value, address(this), _stuff);
deleted

2022-03-15 01:15 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/011.sol
> +      require(balanceMap[msg.sender] >= amount);
deleted

2022-03-15 01:16 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/018.sol
> +        assert (transfer(owner, amount)) ;
changed to require, it should be require

2022-03-15 01:17 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/019.sol
> +        require(!disabled);
updated

2022-03-15 01:18 UTC, cassc commented on benchmarks/verismart/verismart-updated/benchmarks/zeus/019.sol
> +        require(!disabled);
updated

2022-03-15 02:52 UTC, taquangtrung approved these changes

2022-03-15 02:55 UTC, merged

2022-03-15 02:55 UTC, taquangtrung commented
Thanks @cassc! :)