Annot in progress
sbip-sg/discover pull request #37
Opened 2021-11-16 01:50 UTC by tnkhanh

2021-11-16 02:24 UTC, taquangtrung requested changes
Can you merge with the newest code from `develop`, and then format code by `make format`?

2021-11-16 02:40 UTC, tnkhanh commented
> 
> 
> Can you merge with the newest code from `develop`, and then format code by `make format`?

Yes, let me do that

2021-11-16 07:49 UTC, taquangtrung commented
@tnkhanh: any update?

2021-11-16 22:12 UTC, tnkhanh commented
The code is now autoformated

2021-11-17 01:56 UTC, taquangtrung requested changes

2021-11-17 01:56 UTC, taquangtrung commented on lib/discover/discover.h
> +void __assert_bug_integer_overflow_i1(void* ptr) {}
use this assertion: __assert_bug_integer_overflow(void* ptr, int bitwidth)

2021-11-17 01:56 UTC, taquangtrung commented on src/llvm/llinstrument.ml
> +            sprint_int lc_start.line
use `(sprint_int lc_start.line ^ " ") ^ (sprint_int lc_start.col ^ " ") ^ ...` to prevent Ocamlformat from breaking to too many lines

2021-11-17 01:56 UTC, taquangtrung commented on src/llvm/llinstrument.ml
> +
remove unused comments

2021-11-17 05:57 UTC, tnkhanh commented on src/llvm/llinstrument.ml
> +
This comment has been removed

2021-11-17 05:58 UTC, tnkhanh commented on src/llvm/llinstrument.ml
> +            sprint_int lc_start.line
Done!

2021-11-17 05:58 UTC, tnkhanh commented on lib/discover/discover.h
> +void __assert_bug_integer_overflow_i1(void* ptr) {}
assert function format changed

2021-11-17 06:07 UTC, taquangtrung requested changes

2021-11-17 06:07 UTC, taquangtrung commented on src/llvm/llinstrument.ml
> +            else ins) in
Can simplify this code? Something like:

if (start_comp < 0) || 
  (start_comp = 0 && end_comp > 0) ||
  (start_comp = 0 && end_comp = 0 && old_ins.tag < ins.tag) then ...

2021-11-18 01:27 UTC, tnkhanh commented
There is currently an error after some fix:
` error: Invalid record (Producer: 'LLVM13.0.0' Reader: 'LLVM 13.0.0') `
My guess is I'm making the new call on the assert function wrong. Second parameter  `LL.const_int (LL.i32_type llctx) width` might be wrong

2021-11-18 02:29 UTC, tnkhanh commented on src/llvm/llinstrument.ml
> +            else ins) in
Fixed in next commit

2021-11-18 04:00 UTC, merged