Add structure for udiv
sbip-sg/discover pull request #56
Opened 2021-11-29 04:40 UTC by tnkhanh

2021-11-29 04:47 UTC, taquangtrung requested changes

2021-11-29 04:47 UTC, taquangtrung commented on src/dataflow/range.ml
> +    (*TO DO *)
(* TODO *)

2021-11-29 04:47 UTC, taquangtrung commented on src/dataflow/range.ml
> +    let ub = udiv_bound a.range_ub b.range_ub in
This logic is INCORRECT!

2021-11-29 05:37 UTC, tnkhanh commented on src/dataflow/range.ml
> +    let ub = udiv_bound a.range_ub b.range_ub in
Ah, let me think about it.

2021-11-29 05:57 UTC, taquangtrung commented on src/dataflow/range.ml
> +    let ub = udiv_bound a.range_ub b.range_ub in
@tnkhanh : you need to put effort into the work. Cannot just randomly implement the code like that!

2021-11-30 03:39 UTC, tnkhanh commented
My logic to implement next is like this:
If a, b are both positive (unsigned), then `ub(a/b) = ub(a) / lb(b) , lb(a/b) = lb(a) / ub(b)`. This looks simple and I will implement it first
For signed integers, I will divide into four cases: a is positive/negative and b is positive/negative
We also need add Division by zero later.

2021-11-30 03:44 UTC, taquangtrung commented
@tnkhanh: need to think of a general solution for both positive/negative integers.
The algorithm for only positive integers might NOT work for all integers.

2021-11-30 11:56 UTC, taquangtrung commented
@tnkhanh: need to put more effort into the implementation!

2021-12-03 09:02 UTC, tnkhanh commented
I'm working on implementing `Division-by-zero` bug detection.
Initially, I wanted it to be detected  by `check_bug_integer_underflow` and `check_bug_integer_overflow` which is not ideal. This is also difficult because these functions only return one `bug option` when called, they can't both report an `IntegerOverflow` and a `DivisionByZero`
So, my idea now is to implement `check_bug_division_by_zero`. The `check_bug_integer_overflow` will skip the `DivisionByZero` bug and this bug is only detected by `check_bug_division_by_zero`. `check_bug_division_by_zero` will check the range of every divisors to see if it contains 0. 
Is this feasible? @taquangtrung

2021-12-03 09:07 UTC, taquangtrung commented
Yes, separating division_by_zero into a separate bug pass is reasonable.

Do note that the division_by_zero reported by range analysis may contain many false positives (since the range may contain 0, but the actual divisor might not be 0), so need to add a note for future improvement to reduce false positives.

2021-12-06 10:12 UTC, taquangtrung commented on src/dataflow/range.ml
> +      let cmp = compare_bound b (BInt BInt.zero) in
Use `Int64.zero`

2021-12-06 10:13 UTC, taquangtrung commented on src/dataflow/range.ml
> +  let union_range (a : range) (b : range) : range =
Is it still needed?

2021-12-06 10:19 UTC, taquangtrung requested changes

2021-12-06 10:19 UTC, taquangtrung commented on src/dataflow/range.ml
> +      else b2 in
Move out as new separate functions

2021-12-06 10:19 UTC, taquangtrung commented on src/dataflow/range.ml
> +      else b2 in
Repeated code, see above comment!

2021-12-06 10:19 UTC, taquangtrung commented on src/dataflow/range.ml
> +              acc) in
Can improve this part? Look ugly!

2021-12-07 06:17 UTC, tnkhanh commented on src/dataflow/range.ml
> +    let ub = udiv_bound a.range_ub b.range_ub in
fixed

2021-12-07 06:18 UTC, tnkhanh commented on src/dataflow/range.ml
> +      let cmp = compare_bound b (BInt BInt.zero) in
Used `Int64`

2021-12-07 06:22 UTC, merged